import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

import { AuthProvider } from "./lib/context/AuthProvider";
import { ProtectRoute } from "./lib/context/Auth";

export const metadata = {
  title: "e-wallet web",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={inter.className}>
          <AuthProvider>
            <ProtectRoute>
              {children}
            </ProtectRoute>
          </AuthProvider>
        </body>
    </html>
  );
}
